"""Actualizacion de modelo agregado descripcion

Revision ID: 425fbc19d408
Revises: 9c645df7a311
Create Date: 2025-02-14 19:14:07.184451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425fbc19d408'
down_revision: Union[str, None] = '9c645df7a311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Test', sa.Column('description', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'Test', ['description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Test', type_='unique')
    op.drop_column('Test', 'description')
    # ### end Alembic commands ###
