"""Actualizacion de modelo eliminamos descripcion

Revision ID: 4eb5ffd1c21d
Revises: 425fbc19d408
Create Date: 2025-02-14 19:21:39.115434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb5ffd1c21d'
down_revision: Union[str, None] = '425fbc19d408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Test_description_key', 'Test', type_='unique')
    op.drop_column('Test', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Test', sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.create_unique_constraint('Test_description_key', 'Test', ['description'])
    # ### end Alembic commands ###
