"""model update | changes

Revision ID: 823aad83bc00
Revises: f2fea9d796fb
Create Date: 2025-02-15 16:29:15.793248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '823aad83bc00'
down_revision: Union[str, None] = 'f2fea9d796fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Test', sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('Test', 'lista')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Test', sa.Column('lista', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('Test', 'images')
    # ### end Alembic commands ###
