"""Actualizacion de modelo add List colum

Revision ID: f2fea9d796fb
Revises: 4eb5ffd1c21d
Create Date: 2025-02-14 19:36:37.269395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2fea9d796fb'
down_revision: Union[str, None] = '4eb5ffd1c21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Test', sa.Column('lista', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Test', 'lista')
    # ### end Alembic commands ###
